openapi: 3.0.0
info:
  title: 見積算出システム API
  description: ...
  version: 1.0.0
paths:
  /TEST/calc:
    post:
      summary: 工数計算
      tags:
        - calc
      operationId: calcTestApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              description: 工数計算リクエスト
              type: object
              properties:
                projectName:
                  type: string
                autoProductivity:
                  type: boolean
                autoProcessRatios:
                  type: boolean
                productivityFPPerMonth:
                  type: number
                projectType:
                  type: string
                ipaValueType:
                  type: string
                dataFunctions:
                  type: array
                  items:
                    type: object
                    properties:
                      selected:
                        type: boolean
                      name:
                        type: string
                      updateType:
                        type: string
                      fpValue:
                        type: number
                      remarks:
                        type: string
                transactionFunctions:
                  type: array
                  items:
                    type: object
                    properties:
                      selected:
                        type: boolean
                      name:
                        type: string
                      externalInput:
                        type: number
                      externalOutput:
                        type: number
                      externalInquiry:
                        type: number
                      fpValue:
                        type: number
                      remarks:
                        type: string
                processRatios:
                  type: object
                  properties:
                    basicDesign:
                      type: number
                    detailedDesign:
                      type: number
                    implementation:
                      type: number
                    integrationTest:
                      type: number
                    systemTest:
                      type: number
      responses:
        '200':
          description: ...
          content:
            application/json:
              schema:
                description: 工数計算レスポンス
                type: object
                properties:
                  projectName:
                    type: string
                  productivityFPPerMonth:
                    type: number
                  totalFP:
                    type: number
                  totalManMonths:
                    type: number
                  standardDurationMonths:
                    type: number
                  dataFunctions:
                    type: array
                    items:
                      type: object
                      properties:
                        selected:
                          type: boolean
                        name:
                          type: string
                        updateType:
                          type: string
                        fpValue:
                          type: number
                        remarks:
                          type: string
                  transactionFunctions:
                    type: array
                    items:
                      type: object
                      properties:
                        selected:
                          type: boolean
                        name:
                          type: string
                        externalInput:
                          type: number
                        externalOutput:
                          type: number
                        externalInquiry:
                          type: number
                        fpValue:
                          type: number
                        remarks:
                          type: string
                  processRatios:
                    type: object
                    properties:
                      basicDesign:
                        type: number
                      detailedDesign:
                        type: number
                      implementation:
                        type: number
                      integrationTest:
                        type: number
                      systemTest:
                        type: number
                  processFPs:
                    type: object
                    properties:
                      basicDesign:
                        type: number
                      detailedDesign:
                        type: number
                      implementation:
                        type: number
                      integrationTest:
                        type: number
                      systemTest:
                        type: number
                  processManMonths:
                    type: object
                    properties:
                      basicDesign:
                        type: number
                      detailedDesign:
                        type: number
                      implementation:
                        type: number
                      integrationTest:
                        type: number
                      systemTest:
                        type: number
                  processDurations:
                    type: object
                    properties:
                      basicDesign:
                        type: number
                      detailedDesign:
                        type: number
                      implementation:
                        type: number
                      integrationTest:
                        type: number
                      systemTest:
                        type: number
                  errorMessages:
                    type: array
                    items:
                      type: string
  /TEST/export:
    post:
      summary: エクスポート
      tags:
        - export
      operationId: exportApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              description: エクスポートリクエスト
              type: object
              properties:
                projectName:
                  type: string
                productivityFPPerMonth:
                  type: number
                projectType:
                  type: string
                ipaValueType:
                  type: string
                totalFP:
                  type: number
                totalManMonths:
                  type: number
                standardDurationMonths:
                  type: number
                processRatios:
                  type: object
                  properties:
                    basicDesign:
                      type: number
                    detailedDesign:
                      type: number
                    implementation:
                      type: number
                    integrationTest:
                      type: number
                    systemTest:
                      type: number
                processManMonths:
                  type: object
                  properties:
                    basicDesign:
                      type: number
                    detailedDesign:
                      type: number
                    implementation:
                      type: number
                    integrationTest:
                      type: number
                    systemTest:
                      type: number
                processDurations:
                  type: object
                  properties:
                    basicDesign:
                      type: number
                    detailedDesign:
                      type: number
                    implementation:
                      type: number
                    integrationTest:
                      type: number
                    systemTest:
                      type: number
                importFile:
                  type: object
                  properties:
                    name:
                      type: string
                      description: ファイル名
                    content:
                      type: string
                      format: byte
                      description: ファイル内容
                exportFile:
                  type: object
                  properties:
                    name:
                      type: string
                      description: ファイル名
                    content:
                      type: string
                      format: byte
                      description: ファイル内容
                dataFunctions:
                  type: array
                  items:
                    type: object
                    properties:
                      selected:
                        type: boolean
                      name:
                        type: string
                      updateType:
                        type: string
                      fpValue:
                        type: number
                      remarks:
                        type: string
                transactionFunctions:
                  type: array
                  items:
                    type: object
                    properties:
                      selected:
                        type: boolean
                      name:
                        type: string
                      externalInput:
                        type: number
                      externalOutput:
                        type: number
                      externalInquiry:
                        type: number
                      fpValue:
                        type: number
                      remarks:
                        type: string
      responses:
        '200':
          description: ...
          content:
            application/json:
              schema:
                description: エクスポートレスポンス
                type: object
                properties:
                  dataFunctions:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        updateType:
                          type: string
                        fpValue:
                          type: number
                        remarks:
                          type: string
                        selected:
                          type: boolean
                  exportFile:
                    type: object
                    properties:
                      name:
                        type: string
                        description: ファイル名
                      content:
                        type: string
                        description: ファイル内容
                  errorMessages:
                    type: array
                    items:
                      type: string
  /TEST/import:
    post:
      summary: インポート
      tags:
        - import
      operationId: importApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Excel file
      responses:
        '200':
          description: ...
          content:
            application/json:
              schema:
                description: インポートレスポンス
                type: object
                properties:
                  projectName:
                    type: string
                  productivityFPPerMonth:
                    type: number
                  projectType:
                    type: string
                  ipaValueType:
                    type: string
                  totalFP:
                    type: number
                  totalManMonths:
                    type: number
                  standardDurationMonths:
                    type: number
                  processRatios:
                    type: object
                    properties:
                      basicDesign:
                        type: number
                      detailedDesign:
                        type: number
                      implementation:
                        type: number
                      integrationTest:
                        type: number
                      systemTest:
                        type: number
                  processManMonths:
                    type: object
                    properties:
                      basicDesign:
                        type: number
                      detailedDesign:
                        type: number
                      implementation:
                        type: number
                      integrationTest:
                        type: number
                      systemTest:
                        type: number
                  processDurations:
                    type: object
                    properties:
                      basicDesign:
                        type: number
                      detailedDesign:
                        type: number
                      implementation:
                        type: number
                      integrationTest:
                        type: number
                      systemTest:
                        type: number
                  dataFunctions:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        updateType:
                          type: string
                        fpValue:
                          type: number
                        remarks:
                          type: string
                        selected:
                          type: boolean
                  transactionFunctions:
                    type: array
                    items:
                      type: object
                      properties:
                        selected:
                          type: boolean
                        name:
                          type: string
                        externalInput:
                          type: number
                        externalOutput:
                          type: number
                        externalInquiry:
                          type: number
                        fpValue:
                          type: number
                        remarks:
                          type: string
                  errorMessages:
                    type: array
                    items:
                      type: string
