openapi: 3.0.0
info:
  title: 見積算出システム API
  description: ...
  version: 1.0.0
paths:
  /api/TEST/test:
    get:
      tags:
        - test
      summary: テスト
      responses:
        '200':
          description: テスト
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: &ref_0
                    id:
                      type: integer
                    name:
                      type: string
    post:
      tags:
        - test
      summary: テスト
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: *ref_0
      responses:
        '201':
          description: テスト
          content:
            application/json:
              schema:
                type: object
                properties: *ref_0
