openapi: 3.0.0
info:
  title: 見積算出システム API
  description: ...
  version: 1.0.0
paths:
  /TEST/calc:
    post:
      summary: 工数計算
      tags:
        - calc
      operationId: calcTestApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              description: 工数計算リクエスト
              type: object
              properties:
                projectName:
                  type: string
                productivityFPPerMonth:
                  type: number
                projectType:
                  type: string
                ipaValueType:
                  type: string
                importFile:
                  type: object
                  properties:
                    name:
                      type: string
                      description: ファイル名
                    content:
                      type: string
                      format: byte
                      description: ファイル内容
                exportFile:
                  type: object
                  properties:
                    name:
                      type: string
                      description: ファイル名
                    content:
                      type: string
                      format: byte
                      description: ファイル内容
                totalFP:
                  type: number
                manMonth:
                  type: number
                dataFunctions:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      updateType:
                        type: string
                      fpValue:
                        type: number
                      remarks:
                        type: string
                      selected:
                        type: boolean
      responses:
        '200':
          description: ...
          content:
            application/json:
              schema:
                description: 工数計算レスポンス
                type: object
                properties:
                  projectName:
                    type: string
                  productivityFPPerMonth:
                    type: number
                  projectType:
                    type: string
                  ipaValueType:
                    type: string
                  importFile:
                    type: object
                    properties:
                      name:
                        type: string
                        description: ファイル名
                      content:
                        type: string
                        format: byte
                        description: ファイル内容
                  exportFile:
                    type: object
                    properties:
                      name:
                        type: string
                        description: ファイル名
                      content:
                        type: string
                        format: byte
                        description: ファイル内容
                  totalFP:
                    type: number
                  manMonth:
                    type: number
                  dataFunctions:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        updateType:
                          type: string
                        fpValue:
                          type: number
                        remarks:
                          type: string
                        selected:
                          type: boolean
  /TEST/exportTest:
    post:
      summary: エクスポート
      tags:
        - exportTest
      operationId: exportTestApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              description: エクスポートリクエスト
              type: object
              properties:
                projectName:
                  type: string
                productivityFPPerMonth:
                  type: number
                projectType:
                  type: string
                ipaValueType:
                  type: string
                importFile:
                  type: object
                  properties:
                    name:
                      type: string
                      description: ファイル名
                    content:
                      type: string
                      format: byte
                      description: ファイル内容
                exportFile:
                  type: object
                  properties:
                    name:
                      type: string
                      description: ファイル名
                    content:
                      type: string
                      format: byte
                      description: ファイル内容
                totalFP:
                  type: number
                manMonth:
                  type: number
                dataFunctions:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      updateType:
                        type: string
                      fpValue:
                        type: number
                      remarks:
                        type: string
                      selected:
                        type: boolean
      responses:
        '200':
          description: ...
          content:
            application/json:
              schema:
                description: エクスポートレスポンス
                type: object
                properties:
                  dataFunctions:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        updateType:
                          type: string
                        fpValue:
                          type: number
                        remarks:
                          type: string
                        selected:
                          type: boolean
                  exportFile:
                    type: object
                    properties:
                      name:
                        type: string
                        description: ファイル名
                      content:
                        type: string
                        description: ファイル内容
