openapi: 3.0.0
info:
  title: 見積算出システム API
  description: ...
  version: 1.0.0
paths:
  /api/TEST/calc:
    post:
      summary: 工数計算
      tags:
        - calc
      operationId: calcTestApplication
      description: ...
      x-eov-operation-id: calcTestApplication
      x-eov-operation-handler: calcApi
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              description: 工数計算リクエスト
              type: object
              properties:
                totalFP:
                  type: number
                manMonth:
                  type: number
      responses:
        '200':
          description: ...
          content:
            application/json:
              schema:
                description: 工数計算レスポンス
                type: object
                properties:
                  totalFP:
                    type: number
                  manMonth:
                    type: number
